# Generated by Django 4.2.7 on 2023-11-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('seeker', 'Seeker'), ('listener', 'Listener')], default='seeker', max_length=10, verbose_name='User Type'),
        ),
    ]
